services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - database-net
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 5
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw

  adminer:
    image: adminer
    container_name: adminer
    networks:
      - database-net
    ports:
      - "9090:8080"
    restart: always
    depends_on:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    networks:
      - database-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elasticsearch
      - xpack.security.enabled=true # Starting with Elasticsearch 8.x, the default Docker image uses HTTPS by default, but only if you do not override xpack.security.enabled manually.
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data:rw

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - database-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 5
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_USERNAME=redis
      - REDIS_PASSWORD=redis
    command: redis-server --requirepass redis
    volumes:
      - redis-data:/data:rw

networks:
  database-net:
    driver: bridge
    name: database-net

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ~/repositories/bellomuhammad/docker/data/databases/postgres
      o: bind
  elasticsearch-data:
    driver: local
    driver_opts:
      type: none
      device: ~/repositories/bellomuhammad/docker/data/databases/elasticsearch
      o: bind
  redis-data:
    driver: local
    driver_opts:
      type: none
      device: ~/repositories/bellomuhammad/docker/data/databases/redis
      o: bind
